variable_list = [
    {"value": {"value": "fr-FR"}, "context": "AHV", "name": "locale"},
    {"value": {"value": "csw-<INSERT_COMMIT_SHA_HERE>"}, "context": "AHV", "name": "vm_name"},
    {"value": {"value": "gso.lab"}, "context": "AHV", "name": "domain"},
    {"value": {"value": "Stephane Bourdeaud"}, "context": "AHV", "name": "vm_requester_name"},
    {"value": {"value": "stephane.bourdeaud@nutanix.com"}, "context": "AHV", "name": "requester_email"},
    {"value": {"value": "Europe/Paris"}, "context": "AHV", "name": "timezone"},
    {"value": {"value": "10.48.108.5"}, "context": "AHV", "name": "vm_ip"},
    {"value": {"value": "10.48.108.1"}, "context": "AHV", "name": "gateway"},
    {"value": {"value": "22"}, "context": "AHV", "name": "subnet_mask"},
    {"value": {"value": "10.48.104.10"}, "context": "AHV", "name": "dns1"},
    {"value": {"value": "10.48.108.10"}, "context": "AHV", "name": "dns2"},
    {"value": {"value": "default"}, "context": "AHV", "name": "ENV"},

    {"value": {"value": "csw-<INSERT_COMMIT_SHA_HERE>"}, "context": "vSphere", "name": "vm_name"},
    {"value": {"value": "gso.lab"}, "context": "vSphere", "name": "domain"},
    {"value": {"value": "Stephane Bourdeaud"}, "context": "vSphere", "name": "vm_requester_name"},
    {"value": {"value": "stephane.bourdeaud@nutanix.com"}, "context": "vSphere", "name": "requester_email"},
    {"value": {"value": "Europe/Paris"}, "context": "vSphere", "name": "timezone"},
    {"value": {"value": "10.48.108.6"}, "context": "vSphere", "name": "vm_ip"},
    {"value": {"value": "10.48.108.1"}, "context": "vSphere", "name": "gateway"},
    {"value": {"value": "255.255.252.0"}, "context": "vSphere", "name": "subnet_mask"},
    {"value": {"value": "10.48.104.10"}, "context": "vSphere", "name": "dns1"},
    {"value": {"value": "10.48.108.10"}, "context": "vSphere", "name": "dns2"},
    {"value": {"value": "default"}, "context": "vSphere", "name": "ENV"}
]