variable_list = [
    {"value": {"value": "csl-<INSERT_COMMIT_SHA_HERE>"}, "context": "AHV", "name": "vm_name"},
    {"value": {"value": "gso.lab"}, "context": "AHV", "name": "domain"},
    {"value": {"value": "Stephane Bourdeaud"}, "context": "AHV", "name": "vm_requester_name"},
    {"value": {"value": "stephane.bourdeaud@nutanix.com"}, "context": "AHV", "name": "requester_email"},
    {"value": {"value": "10.48.108.79"}, "context": "AHV", "name": "vm_ip"},
    {"value": {"value": "10.48.108.1"}, "context": "AHV", "name": "gateway"},
    {"value": {"value": "255.255.252.0"}, "context": "AHV", "name": "subnet_mask"},
    {"value": {"value": "10.48.104.10"}, "context": "AHV", "name": "dns1"},
    {"value": {"value": "10.48.108.10"}, "context": "AHV", "name": "dns2"},
    {"value": {"value": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9GE/gov8gOPsSkKVeejG5NYTJTQGNFCsJOXFcszhd1s1ixS1ClVZs3MduB1fWSvY8Vjzs+jD5VkW7SdwxEQQmOvyF8sHGNM1s4FGNgnRIvKXlPaXQSe9TUEl52xJa7G0JwggiG4kNgCtJmunK9cXZMj+iTQqSwdGvidOFdMxTbmSjlTNEE4kMIP4jiyZEKztVbz4i9+bI/Sq8cQVX+pNF6XTjxqUgDH15KIejnXw6QDH26yv6KWbSjtRl+8HvE1yNtJh9yXDEJ1pt4jcvE2SHNfFYlY8HM9qyymeVkL7SzL3u6dmkN7ospqiNgJVEW/iOATUHICLZpSXj1kr73xFB"}, "context": "AHV", "name": "public_key"},
    {"value": {"value": "default"}, "context": "AHV", "name": "ENV"},

    {"value": {"value": "csl-<INSERT_COMMIT_SHA_HERE>"}, "context": "vSphere", "name": "vm_name"},
    {"value": {"value": "gso.lab"}, "context": "vSphere", "name": "domain"},
    {"value": {"value": "Stephane Bourdeaud"}, "context": "vSphere", "name": "vm_requester_name"},
    {"value": {"value": "stephane.bourdeaud@nutanix.com"}, "context": "vSphere", "name": "requester_email"},
    {"value": {"value": "10.48.108.80"}, "context": "vSphere", "name": "vm_ip"},
    {"value": {"value": "10.48.108.1"}, "context": "vSphere", "name": "gateway"},
    {"value": {"value": "255.255.252.0"}, "context": "vSphere", "name": "subnet_mask"},
    {"value": {"value": "10.48.104.10"}, "context": "vSphere", "name": "dns1"},
    {"value": {"value": "10.48.108.10"}, "context": "vSphere", "name": "dns2"},
    {"value": {"value": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9GE/gov8gOPsSkKVeejG5NYTJTQGNFCsJOXFcszhd1s1ixS1ClVZs3MduB1fWSvY8Vjzs+jD5VkW7SdwxEQQmOvyF8sHGNM1s4FGNgnRIvKXlPaXQSe9TUEl52xJa7G0JwggiG4kNgCtJmunK9cXZMj+iTQqSwdGvidOFdMxTbmSjlTNEE4kMIP4jiyZEKztVbz4i9+bI/Sq8cQVX+pNF6XTjxqUgDH15KIejnXw6QDH26yv6KWbSjtRl+8HvE1yNtJh9yXDEJ1pt4jcvE2SHNfFYlY8HM9qyymeVkL7SzL3u6dmkN7ospqiNgJVEW/iOATUHICLZpSXj1kr73xFB"}, "context": "vSphere", "name": "public_key"},
    {"value": {"value": "default"}, "context": "vSphere", "name": "ENV"}
]